version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/kick_live_status"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/kick_live_status"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
